CREATE TABLE categories(
	id serial primary key,
	name text
);

CREATE TABLE restaurent(
	id serial primary key,
	name text,
	location text,
	price integer,
	denomination text,
	Tags text,
	rating integer,
	category integer references categories(id)
);

CREATE TABLE reviews(
	id serial primary key,
	restaurent_id integer references restaurent(id),
	comment text default '',
	rating integer default 1
);


----MOCK DATA----
insert into categories (name) values ('Fast food')
,('Fast casual')
,('Casual dining')
,('Premium casual')
,('Family style')
,('Fine dining');

insert into restaurent (name) 
values
('HOTELNAME')
,('TheOberoiCecil')
,('TheLalitGrandPalace')
,('HotelFatehPrakashPalace')
,('ShivNiwasPalace')
,('SavoyHotel')
,('RaheemResidency')
,('NoorUsSabahPalace')
,('ThePanjimInn')
,('BalaramPalaceResort')
,('NilambagPalaceHotel')
,('TheFortRamgarh')
,('TheJudgesCourt')
,('ThePalace')
,('TheCastleNaggar')
,('HotelCherthalaHouse')
,('HeritagaMethanam')
,('OldLighthouseBristowHotel')
,('HotelLeColonial')
,('KunnathurManaAyurvedaHeritage')
,('OldHarbourHotel')
,('CoconutLagoon')
,('BeachHotel')
,('PalakkadHeritageHotels')
,('SomatheeramAyurvedicBeachResort(P)Ltd')
,('TheHillwayHeritage')
,('AhilyaFort')
,('HotelRockEndManor')
,('SatpuraRetreat')
,('HotelSheeshMahal')
,('JehanNumaPalaceHotel')
,('LEDUPLEIX')
,('Calve')
,('WelcomeHeritage,KhimsarFort')
,('TheBagh')
,('GajnerPalace')
,('TheLaxmiNiwasPalace')
,('ChomuPalace')
,('BissauPalace')
,('DeogarhResorts')
,('ShikarbadiHotel')
,('WelcomHeritage-KoolwalKothi')
,('AjitBhawan')
,('HotelSamodePalace')
,('RajNiwasPalace')
,('HotelCastleMandawaPvt.Ltd.')
,('RohetGarh')
,('LakePicholaHotel')
,('TheRamgarhLodge')
,('HotelIndraVillas')
,('SinghasanHaveli')
,('FortKhejarla')
,('SardargarhHeritageHotel')
,('TheSawaiMadhopurLodge')
,('KarniBhawanPalace')
,('NorkhillHotel')
,('Visalam')
,('HotelFairhavensHolidayHome')
,('TheNainiRetreat')
,('TheElginHotel')
,('TajFalaknumaPalace')
,('ITCHOTELKAKATIYA')
,('ErosHotelManagedbyHilton')
,('TheAshok')
,('HotelImperial')
,('HyattRegencyDelhi')
,('ITC-TheMaurya')
,('LeMeridienHotel')
,('TajPalaceHotel')
,('TheLalit')
,('TheOberoi-NewDelhi')
,('Aman,NewDelhi')
,('TheHotelLeelaPalaceKempinski')
,('RivieraDeGoaResort')
,('VivantabyTaj-Panaji')
,('VivantabyTaj-Holiday')
,('BellTowerResortsPvt.Ltd.')
,('HotelRamadaCaravelaBeachResort')
,('VivantaByTaj-FortAguada')
,('ThLalitGolf&SpaResortGoa')
,('ResortRio')
,('HotelCidadedeGoa')
,('MajordaBeachResort')
,('TheLeelaKempinski,Goa')
,('HotelTrident-Gurgaon')
,('TheLeelaKempinski-Gurgaon')
,('TheBristolHotel')
,('WildflowerHall')
,('VivantabyTaj-Whitefield')
,('HotelGoldenPalmsHotel&Spa')
,('ITCHotelWindsor&Towers')
,('TheTajWestEnd')
,('SheratonBangloreatBrigadeGateway')
,('TheOberoiBangalore')
,('VivantabyTaj-Bangalore')
,('ParkPlaza')
,('DreamHotelCochin')
,('VivantabyTaj-Bekal')
,('TheLalitResorts&SpaBekal')
,('VivantaByTaj-Kovalam')
,('Vivantaby-TajMalabar')
,('TheRavizKollam')
,('KovalamResortPrivateLimited')
,('TheGrandTempleView')
,('HotelChandela')
,('ChaletHotel')
,('FourSeasonsHotel')
,('HOTELSAHARASTAR')
,('HyattRegencyMumbai')
,('LeRoyalMeridien')
,('Sun-n-SandHotelsPvt.Ltd.')
,('TheTajMahalPalace&Tower')
,('HotelLeMeridien')
,('HotelITCGrandCentral')
,('TheLeelaKempinski')
,('TheOberoi,Mumbai')
,('TheWestinMumbaiGardenCity')
,('FariyasResort,Lonavla')
,('Trident,NarimanPoint')
,('TajLandsEnd')
,('Trident-Bhubaneswar')
,('HotelMayfairLagoon')
,('ISTAAmritsar')
,('SheratonRajputanaHotel')
,('TheOberoiRajvilas')
,('TheOberoiUdaivilas')
,('CountryInn&SuitesByCarlson')
,('TheLeelaPalaceKempinski')
,('JAIMAHALPALACEHOTEL')
,('MayfairSpa&Resort')
,('TajMountRoad')
,('THEPARK')
,('VivantabyTaj-FishermansCove')
,('TajCoromandel')
,('LeRoyalMeridienChennai')
,('ITCTheMughal')
,('JaypeeGreensGolf&SpaResort')
,('VivantabyTaj')
,('TajGangesVaranasi')
,('RadissonHotel')
,('RadissonMBDHotel')
,('HolidayRegency')
,('JaypeeResidencyManor')
,('ITCSonar')
,('HotelIstaHyderabad')
,('HotelNovotelHyderabad')
,('NovotelHyderabadAirport')
,('TheGatewayHotel')
,('TajDeccan-Hyderabad')
,('LeoMeridianInfrastructure')
,('HotelMountview')
,('HotelCrownePlazaToday')
,('VivantabyTajAmbassador')
,('FortuneSelectRegina')
,('BogmalloBeachResort')
,('DEVAAYAAYURVEDASPARESORT')
,('HolidayInnResort')
,('TheCrownGoa')
,('HotelNeoMajestic')
,('TheKenilworthBeachResort&Spa')
,('HotelLaCalypsoGetAways.')
,('The"O"')
,('Sun-n-SandHotel')
,('TheImperialPalace')
,('LeMeridien')
,('TheGatewayHotelUmmed')
,('TheGalaxyHotel')
,('THECHANCERYPAVILION')
,('TheZuri-Whitefield')
,('FortuneParkJ.P.Palace')
,('HotelLeMeridien-Bangalore')
,('MovenpickHotel&SpaBangalore')
,('ClubMahindraLakeview')
,('TheQuilonBeachHotel')
,('TheElephantCourt')
,('TurtleOnTheBeach')
,('CasinoHotel')
,('Trident,Cochin')
,('TheGatewayHotel-Ernakulam')
,('KadavuResort&AyurvedaCentre')
,('TheMuthootPlazaHotel')
,('TajResidency-Trivandrum')
,('HotelRamada-Khajuraho')
,('RadissonJassHotel')
,('GrandSarovarPremiere')
,('HotelMeluha')
,('HotelTungaRegencyPvt.Ltd.')
,('RamadaPlazaPalmGrove')
,('TheShalimarHotel')
,('THEPRIDEHOTEL')
,('FourPointsBySheraton')
,('TajBlueDiamond')
,('TheOHotel')
,('TajResidency-Aurangabad')
,('HotelSeaPrincess')
,('TheGatewayHotel')
,('HotelParcEstique')
,('RadissonWindsorHotel')
,('MajesticParkPlaza')
,('HotelMansingh')
,('HotelTrident,Jaipur')
,('FortuneSelectMetropolitan-Jaipur')
,('ChokhiDhani')
,('InderResidency')
,('DenzongRegency')
,('TheGatewayHotelPasumalaiMadurai')
,('RadissonHotelGRT')
,('Trident-Chennai')
,('HotelClarksShiraz')
,('HotelTrident-Agra')
,('CountryInn&SuitesbyCarlson.')
,('RadissonHotelVaranasi')
,('TheGatewayHotel,Agra')
,('HotelHindusthanInternational')
,('SwissotelKolkataNeotiaVista')
,('TheGolkonda')
,('PalmBeachHotel')
,('QUALITYINNDVMANOR')
,('BestWesternAmruthaCastle')
,('HotelGreenPark')
,('HotelRajMahal')
,('HotelNatraj')
,('HotelTheRoyalPlaza')
,('HotelCityPark')
,('HotelDiplomat')
,('MaidensHotel')
,('TheConnaught')
,('HotelVikram')
,('LazylagoonSarovarPorticoSuites')
,('SunVillageResort')
,('WHISPERINGPALMSBEACHRESORT')
,('TheMetropoleHotel')
,('HotelFortunePalace')
,('FortuneInnHaveli')
,('HotelTheGrandBhagwati')
,('OptusSarovarPremiereHotel')
,('ParkPremier')
,('TheBellaVista')
,('FortuneSelectGlobal')
,('CourtyardByMarriott')
,('FortuneParkJ.P.Celestial')
,('TheGatwwayHotel-Chikmagalur')
,('RajResidency')
,('HotelMauryaRajadhani')
,('KeysHotels')
,('HotelBlueNile')
,('HotelAmruthaaInternational')
,('FragrantNatureRetreatandResortPvt.Ltd')
,('HotelPresidency')
,('HotelRajRegency')
,('ATSResidency')
,('TheRoyaleGardens')
,('HotelSrivatsaRegency')
,('HotelHillsPark')
,('NeelamabariSuite')
,('ExcaliburHotels&Resorts')
,('RajResidency')
,('MuthootCardamomCountyResort')
,('HotelWhiteDammarInternational')
,('HotelSPGrandDays')
,('HotelPeninsulaParkResidency')
,('HotelIndraprastha')
,('HotelMangalaTowers')
,('HotelSooryaRegency')
,('HotelMoonlitRegency')
,('HotelSkyPearl')
,('TheRoyalFort')
,('HotelSooryaGalaxy')
,('CochinSeaportHotel')
,('TheAvenueRegent')
,('SpiceVillage')
,('HotelMidhilaRegency')
,('HotelSooryaSwagat')
,('TheHotelElegance')
,('KRGrandResidency')
,('HotelDonaCastle')
,('HotelFairmont')
,('HotelAnandhaInnPvt.Ltd.')
,('NiyaRegency')
,('TheSouthPark')
,('UdaySamudraLeisureBeachHotel')
,('SEASONSSERVICEAPARTMENTS')
,('HOTELBAWAINTERNATIONAL')
,('HotelCourtyardByMarriott')
,('HotelMidtownPritam')
,('HotelTrident')
,('HotelTungaRegale')
,('RameeGuestlineHotel')
,('K.RahejaCorp.Pvt.Ltd."TheResort"')
,('HotelSagarPlaza')
,('TheCentralParkHotel')
,('HolidayInnMumbaiInternationalAirport')
,('TheEmerald')
,('HotelPoloTower')
,('M.K.HOTEL')
,('THEMAYAHOTEL(MayaInnsLtd.)')
,('HotelRitzPlaza')
,('CountryIn&Suites,Ajmer')
,('TheRoyalPlaza')
,('TheResidencyTowers')
,('HotelSangam')
,('QualityInnSabari')
,('TheSaveraHotel')
,('HotelRajPark(P)Ltd.')
,('FortuneInnGrazia')
,('CountryInn&SuitesbyCarlson-Haridwar')
,('ThePeerlessInn');

update restaurent set location='Chennai', price=100, denomination='INR', tags='south indian,Andhra,Chinese,Arabian', rating=4, category=id%6+1;
update restaurent set location='Bangalore', price=300, denomination='INR', tags='south indian,Andhra,Chinese,Arabian', rating=3 where id%3=0;
update restaurent set location='Hyderabad', price=100, denomination='INR', tags='North indian,Andhra,', rating=2 where id%2=0;
update restaurent set location='Hyderabad', price=100, denomination='INR', tags='Andhra', rating=1 where id%7=0;
update restaurent set location='Hyderabad', price=100, denomination='INR', tags='Japanese,Andhra,', rating=5 where id%5=0;


